# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lwsuv' do
    inhibit_all_warnings!
    # pod 'SDWebImage', '4.4.1'
    pod 'MJRefresh' , '3.1.15.3'
    pod 'Masonry', '1.1.0'
    pod 'IQKeyboardManager' , '6.0.4'
    # pod 'AFNetworking' , '3.2.1'
    pod 'MJExtension' , '3.0.15'
    pod 'FMDB' , '2.7.2'
    pod 'JPush' , '3.0.9'

end
